{
 "title": "TraceRoute",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "query_dest", "label": "dest", "query": "101" },
   { "name": "query_ttl", "label": "ttl", "query": "19" },
   { "name": "query_respadd", "label": "respRouter" }
  ]
 },
 "panels": [
  {
   "title": "Latency by TTL",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    TTL,\n    avg(Delay)\nFROM $table\n\nWHERE $timeFilter\n$conditionalTest(AND Dest like '%$query_dest%',$query_dest)\n$conditionalTest(AND RespAddr like '%$query_respadd%',$query_respadd)\n$conditionalTest(AND TTL = $query_ttl,$query_ttl)\n\nGROUP BY TTL,t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(Timestamp), 10) * 10) * 1000 as t,\n    TTL,\n    avg(Delay)\nFROM default.zprobe\n\nWHERE Timestamp >= toDateTime(1652061700) AND Timestamp <= toDateTime(1652083300)\n AND Dest like '%google%' \n \n \n\nGROUP BY TTL,t\n\nORDER BY t",
     "round": "0s",
     "table": "zprobe"
    }
   ]
  },
  {
   "title": "Loss by TTL",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    TTL,\n    avg(Loss)\nFROM $table\n\nWHERE $timeFilter\n$conditionalTest(AND Dest like '%$query_dest%',$query_dest)\n$conditionalTest(AND RespAddr like '%$query_respadd%',$query_respadd)\n$conditionalTest(AND TTL = $query_ttl,$query_ttl)\n\nGROUP BY TTL,t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(Timestamp), 2) * 2) * 1000 as t,\n    TTL,\n    avg(Loss)\nFROM default.zprobe\n\nWHERE Timestamp >= toDateTime(1652163089) AND Timestamp <= toDateTime(1652166689)\n AND Dest like '%202%' \n \n AND TTL = 0 \n\nGROUP BY TTL,t\n\nORDER BY t",
     "round": "0s",
     "table": "zprobe"
    }
   ]
  },
  {
   "title": "Jitter by TTL",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    TTL,\n    avg(Jitter)\nFROM $table\n\nWHERE $timeFilter\n$conditionalTest(AND Dest like '%$query_dest%',$query_dest)\n$conditionalTest(AND RespAddr like '%$query_respadd%',$query_respadd)\n$conditionalTest(AND TTL = $query_ttl,$query_ttl)\n\nGROUP BY TTL,t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(Timestamp), 1) * 1) * 1000 as t,\n    TTL,\n    avg(Jitter)\nFROM default.zprobe\n\nWHERE Timestamp >= toDateTime(1652162814) AND Timestamp <= toDateTime(1652164614)\n AND Dest like '%netflix%' \n \n \n\nGROUP BY TTL,t\n\nORDER BY t",
     "round": "0s",
     "table": "zprobe"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    Host,\n    Dest,\n    TTL,\n    uniq(RespAddr) as ECMPNum,\n    groupUniqArray(RespAddr) as Addr,\n\n    groupUniqArray(City) as City,\n    groupUniqArray(Country) as Country,\n    groupUniqArray(ASN) as SP,\n    groupUniqArray(SPName) as SPName,\n    avg(Delay) as Delay,\n    avg(Jitter) as Jitter,\n    avg(Loss) as Loss\n      FROM default.zprobe\n      WHERE $timeFilter\n      $conditionalTest(AND Dest like '%$query_dest%',$query_dest)\n      $conditionalTest(AND RespAddr like '%$query_respadd%',$query_respadd)\n      $conditionalTest(AND TTL = $query_ttl,$query_ttl)\nGROUP BY Host,Dest,TTL\nORDER BY Host,Dest,TTL",
     "rawQuery": "SELECT\n    Host,\n    Dest,\n    TTL,\n    uniq(RespAddr) as ECMPNum,\n    groupUniqArray(RespAddr) as Addr,\n\n    groupUniqArray(City) as City,\n    groupUniqArray(Country) as Country,\n    groupUniqArray(ASN) as SP,\n    groupUniqArray(SPName) as SPName,\n    avg(Delay) as Delay,\n    avg(Jitter) as Jitter,\n    avg(Loss) as Loss\n      FROM default.zprobe\n      WHERE Timestamp >= toDateTime(1652172393) AND Timestamp <= toDateTime(1652176052)\n       AND Dest like '%202%' \n       \n       \nGROUP BY Host,Dest,TTL\nORDER BY Host,Dest,TTL",
     "round": "0s",
     "table": "zprobe"
    }
   ]
  }
 ]
}